config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :tasks do
    collection do
      post :clear_completed
      post :complete_all
      post :uncomplete_all
    end

    member do
      post :mark_as_done
      post :mark_as_undone
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  scope :are_done, -> (is_done) { where is_done: is_done }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @task = Task.new
    @there_are_done_items = Task.find_by(:is_done => true)

    if(params[:editing_task] != nil)
      @editing_task = Task.find_by(:id => params[:editing_task])
    end

    if(params[:filter] == nil)
      @active_filter = 'all'
      @visible_tasks = Task.all
    else
      @visible_tasks = Task.where(nil)
      @active_filter = params[:filter]

      if params[:filter] == 'are_done'
        @visible_tasks = @visible_tasks.are_done(true)
      elsif params[:filter] == 'are_undone'
        @visible_tasks = @visible_tasks.are_done(false)
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout :resolve_layout

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def edit
    @submit_url = task_path
    @task = Task.find_by(id: params[:id])
  end

  def new
    @submit_url = tasks_path
    @task = Task.new
  end

  def complete_all
    puts params
    tasks = params[:tasks]
    tasks.each do |task|
      task.is_done = true
      task.save
    end

    redirect_back fallback_location: 'pages#index'
  end

  def uncomplete_all
    puts params
    tasks = params[:tasks]
    tasks.each do |task|
      task.is_done = false
      task.save
    end

    redirect_back fallback_location: 'pages#index'
  end

  def create
    @task = Task.new(post_params)
    @task.save
    redirect_back fallback_location: 'pages#index'
  end

  def update
    @task = Task.find_by(id: params[:id])
    if @task.update(post_params)
      if /\A?editing_task=[^&]+&*/.match request.referrer
        redirect_to request.referrer.sub(/\A?editing_task=[^&]+&*/, '')
      else
        redirect_back fallback_location: 'pages#index'
      end
    else
      render 'edit'
    end
  end

  def clear_completed
    Task.where(:is_done => true).each do |task|
      task.destroy
    end

    redirect_back fallback_location: 'pages#index'
  end

  def destroy
    @task = Task.find_by(id: params[:id])

    @task.destroy
    redirect_back fallback_location: 'pages#index'
  end

  def mark_as_done
    @task = Task.find_by(id: params[:id])

    @task.is_done = true
    if @task.save
      redirect_back fallback_location: 'pages#index'
    else
      render 'edit'
    end
  end

  def mark_as_undone
    @task = Task.find_by(id: params[:id])

    @task.is_done = false
    if @task.save
      redirect_back fallback_location: 'pages#index'
    else
      render 'edit'
    end
  end

  private def post_params
    params.require(:task).permit(:description, :is_done, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RorTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/index.html.haml
%main.page

  %h1
    Welcome to the official page of "Elias' struggle with RoR"

  %p
    ToDo MVC in Rails.

  = render 'tasks/quick_form', task: @task, submit_url: tasks_path;
  = render 'tasks/list', tasks: @visible_tasks, editing_task: @editing_task;

  -if !@visible_tasks.all? {|task| task.is_done}
    = link_to "<span class=\"\">Check all</span>".html_safe, complete_all_tasks_path(:tasks => @visible_tasks), method: :post
  -else
    = link_to "<span class=\"\">Uncheck all</span>".html_safe, uncomplete_all_tasks_path(:tasks => @visible_tasks), method: :post

  = link_to "<span class=\"filter #{"active"if @active_filter == "all"}\">all</span>".html_safe
  = link_to "<span class=\"filter #{"active"if @active_filter == "are_undone"}\">active</span>".html_safe, :filter => "are_undone"
  = link_to "<span class=\"filter #{"active"if @active_filter == "are_done"}\">completed</span>".html_safe, :filter => "are_done"
  - if @there_are_done_items
    = link_to '<span class="action">clear completed</span>'.html_safe, clear_completed_tasks_path, method: :post

app/views/tasks/_form.html.haml
=form_for @task, url: @submit_url do |f|
  =f.label :description
  %br
  =f.text_field :description
  %br
  =f.label :is_done
  %br
  =f.check_box :is_done
  %br
  =f.submit

app/views/tasks/_list.html.haml
%ul.tasks.list
  - tasks.each do|task|
    %li.task.list_item{:data => {:id => task.id}}
      - if editing_task != task
        .description{:class => ('done' if task.is_done)}
          = task.description

        - if(task.is_done)
          = link_to "<i>uncheck</i>".html_safe, mark_as_undone_task_path(task), method: :post
        - else
          = link_to "<i>check</i>".html_safe, mark_as_done_task_path(task), method: :post

        = link_to "<i>delete</i>".html_safe, task_path(task), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }

      - else
        = render 'tasks/quick_form', task: task, submit_url: task_path(task);

app/views/tasks/_quick_form.html.haml
=form_for task, url: submit_url do |f|
  =f.text_field :description, placeholder: 'What needs to be done?'
  =f.hidden_field :is_done
  =f.hidden_field :id

app/views/tasks/edit.html.haml
= render "form"

app/views/tasks/index.html.haml
= render 'list'

app/views/tasks/new.html.haml
=form_for :task, url: tasks_path do |f|
  =f.label :description
  %br
  =f.text_field :description
  %br
  -# =f.label :is_done
  -# %br
  -# =f.check_box :is_done
  %br
  =f.submit

app/views/tasks/show.html.haml
= @task.description